[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200