[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/handler/:splat"
  status = 200 = 200